### PR TITLE
remove scipy and torch from requirements

### PR DESCRIPTION
**Pull request by yamaguchi1024**

### CODE REVIEW

**Comment by alexreinking** [comment]
You're missing `import pytest`.

**Comment by alexreinking** [comment]
Is `test_winograd.py` worth keeping at all? It looks from the comments like it wasn't even a correct test to begin with. It would be nicer to fix the test (perhaps by validating the values offline and then committing it as the golden output), but we could also just delete it.

**Comment by yamaguchi1024** [comment]
I would like to keep the test. It's at least compliant with what Tian had implemented for his job.

**Comment by yamaguchi1024** [comment]
Although I do agree that it can be optimized more.

**Comment by yamaguchi1024** [comment]
And, it is not that "it was not the correct test, to begin with". It's just that we can expand the matrix thus can delete zero coefficients so that it becomes more optimal.

**Comment by alexreinking** [comment]
What does `# TODO: finish test, validate output (returns NaN right now)` mean, then?

**Comment by yamaguchi1024** [comment]
The test needs to be validated, but removing the torch dependency is a different issue. Python 3.10 doesn't support torch yet (and torch is a huge dependency), and not all the users need to run winograd test.

**Comment by alexreinking** [comment]
> The test needs to be validated, but removing the torch dependency is a different issue. Python 3.10 doesn't support torch yet (and torch is a huge dependency)

It's not that different. This way is somewhat vacuous. We could also "remove" all of our dependencies by skipping every test and turning our whole API surface into one big no-op. Torch is a huge dependency we probably shouldn't have _even if_ it supported Python 3.10.

> and not all the users need to run winograd test.

None of our _users_ need to run any test. They need to use the library. The developers and CI need to run the tests.

**Comment by yamaguchi1024** [comment]
> None of our users need to run any test. They need to use the library. The developers and CI need to run the tests.

Sure. Ideally, we probably want to separate EXO dependency and EXO test dependency.

> Torch is a huge dependency we probably shouldn't have even if it supported Python 3.10.

I'm on board with that

**Comment by yamaguchi1024** [comment]
This PR is ready for review @gilbo @alexreinking

**Review by gilbo — APPROVED** [review]

**Pull request merged**
